version: 0.1
phases:
  install:
    commands:
      - npm install -g elm
      - sudo apt-get update -qq && sudo apt-get install -yqq apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update -qq && sudo apt-get install -yqq yarn
      - yarn install
  pre_build:
    commands:
      - echo Nothing to do in pre-build...
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - aws s3 sync dist/ s3://thuringer.us
      - aws cloudfront create-invalidation --distribution-id E2JRDISJTFNDDC --paths /index.html
      - echo Build completed on `date`